export { default as Home } from "./Home"
export { default as Work } from "./Opportunities"
export { default as Account } from "./Account"
export { default as EmailVerification } from "./EmailVerification"
export { default as Opportunities } from "./Opportunities"
export { default as Projects } from "./Projects"
export { default as Project } from "./Project"
export { default as Support } from "./Support"
